version: "3.6"
services:
  graphql:
    build:
      context:
        .
      args:
        - HOME_DIR=/home/graphql/
    working_dir: /home/graphql
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/home/graphql
      - node_modules_graphql:/home/graphql/node_modules
    ports:
      - "8081:8081"
      
volumes:
  node_modules_graphql: